version = 1
SPDX-PackageName = "Chimera"
SPDX-PackageSupplier = "Huang Rui <vowstar@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/rgwan/chimera"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Huang Rui <vowstar@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".gitignore", "flake.lock", "sail/h8300.sail_project", "tools/jtag2gdb/Cargo.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Huang Rui <vowstar@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["doc/**.md", "doc/diagrams/*.drawio.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Huang Rui <vowstar@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "bench/dhrystone/upstream/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "1984 Reinhold P. Weicker"
SPDX-License-Identifier = "LicenseRef-Dhrystone"
